spring:
  application:
    name: facient

  config:
    activate:
      profile: dev

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      session-timeout-ms: 15000
      heartbeat-interval-ms: 3000
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  datasource:
    mysql:
      jdbc-url: jdbc:mysql://localhost:3306/community_exchange
      username: root
      password: SaiRam$2025
      driver-class-name: com.mysql.cj.jdbc.Driver

    postgres:
      jdbc-url: jdbc:postgresql://localhost:5432/community_exchange
      username: postgres
      password: SaiRam$2025
      driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  data:
    redis:
      host: localhost
      port: 6379

    logging:
      level:
        root: INFO
        com.community.exchange.facient: DEBUG

jwt:
  secret: "change_this_to_a_long_secure_secret_key_at_least_32_chars"
  expiration: 3600000

server:
  port: 8080

management:
  tracing:
    sampling:
      probability: 1.0  # enable full sampling (100%)
    enable: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
